#%RAML 1.0 ResourceType

usage: Use this type for controller-type resources

uses:
  errorWarning: ../libraries/error_warning.raml
post:
  headers:
    log_id?:
      description: Propagated identifier from top to bottom. Used to track errors or transactions
  responses:
    303:
      headers:
        Location:
          description: Resource URI
          type: string
    400:
      description: Non valid petition
      body:
        application/json:
          type: errorWarning.ErrorWarning
    405:
      description: Non valid parameters
      body:
        application/json:
          type: errorWarning.ErrorWarning
    422:
      description: Unprocessable Entity
      body:
        application/json:
          type: errorWarning.ErrorWarning
    500:
      description: Internal Error
    503:
      description: Unavailable Service
