#%RAML 1.0 ResourceType

usage: Use this type to define filterable list resources

description: |
  **Warning**
  <ul>
    <li>In case of using filters, the meaning of "&" (query parameters separator)
    is defined according to the context, it can be AND or IN:
      <ol>
        <li>
          **"AND"**, when the filter criterion is composed of a
          sequence of attributes that are different from each other.<p>
          Example: ?a=1&b=2&c=3, should be<p>
           *(((a = 1) AND (b = 2)) AND (c = 3))*<p>
        </li>
        <li>
          **"IN"**, when the filter criterion is composed of a sequence of expressions
          applied to the same attribute. Whenever repeated parameters are found, they
          are grouped into an IN expression.<p>
          Example: ?a=1&b=2&a=3, should be<p>
          *a IN (1, 3) AND (b = 2)*<p>
        </li>
      </ol>
    </li>
  </ul>

uses:
  errorWarning: ../libraries/error_warning.raml

head?:
  headers:
    log_id?:
      description: Propagated identifier from top to bottom. Used to track errors or transactions
  responses:
    200:
      description: One or more resource found
      headers:
        Content-Location:
          description: Resource URI
        Last-Modified:
          description: Last update
    204:
      description: No resource found with specified criteria
    400:
      description: Non valid petition
    422:
      description: Unprocessable Entity
    500:
      description: Internal Error
    501:
      description: Not Implemented
    503:
      description: Unavailable Service
get?:
  headers:
    log_id?:
      description: Propagated identifier from top to bottom. Used to track errors or transactions
  responses:
    200:
      headers:
        Content-Location:
          description: Resource URI
    400:
      description: Non valid petition
      body:
        application/json:
          type: errorWarning.ErrorWarning
    422:
      description: Unprocessable Entity
      body:
        application/json:
          type: errorWarning.ErrorWarning
    500:
      description: Internal Error
    501:
      description: Not Implemented
    503:
      description: Unavailable Service
delete?:
  headers:
    log_id?:
      description: Propagated identifier from top to bottom. Used to track errors or transactions      
put?:
  headers:
    log_id?:
      description: Propagated identifier from top to bottom. Used to track errors or transactions
post?:
  headers:
    log_id?:
      description: Propagated identifier from top to bottom. Used to track errors or transactions
  responses:
    201:
      headers:
        Content-Location:
          description: Resource URI
          type: string
          example: <<baseUri>><<resourcePath>>/1
    400:
      description: Non valid petition
      body:
        application/json:
          type: errorWarning.ErrorWarning
    405:
      description: Non valid parameters
      body:
        application/json:
          type: errorWarning.ErrorWarning
    409:
      description: Resource alredy exists
      body:
        application/json:
          type: errorWarning.ErrorWarning
    422:
      description: Unprocessable Entity
      body:
        application/json:
          type: errorWarning.ErrorWarning
    500:
      description: Internal Error
    501:
      description: Not Implemented
    503:
      description: Unavailable Service
