#%RAML 1.0 Library
usage: |
  Apply to a method to add view support.

  Is up to the designer to explain the meaning of types of view
  Field list is especified as a parameter, so, it's not possible to verify
  if they really exists. Caution is required.
traits:
  Viewable:
    queryParameters:
      view?:
        description: |
          Allows to ask for a simplified or detailed version of the
          response. Possible values are: _<<views>>_
        type: string
        pattern: "((<<views>>),?)+"
