#%RAML 1.0 Library
uses:
  base: ./base.raml
types:

  StudentResponse:
    description: |
      Student information
    properties:
      id:
        type: base.StudentId
      first_name:
        type: base.IndividualName
      last_name:
        type: base.IndividualName
      document_number:
        type: base.id_document_number
      birth_date:
        type: date-only
      gender:
        type: base.Gender
      height:
        type: number
      weight:
        type: number
      email:
        type: base.Email
      creation_date_time:
        type: datetime-only

  StudentsPostResponseData:
    description: |
      Wrapper for a student post request
    properties:
      data: 
        type: StudentResponse