#%RAML 1.0 Library
uses:
  base: ./base.raml
types:

  SubjectRequest:
    description: |
      Subject information
    properties:
      name:
        type: base.SubjectName

  SubjectsUpdateRequestData:
    description: |
      Wrapper for a subject update request
    properties:
      data: 
        type: SubjectRequest
